name: Ejemplo matriz

on: 
  workflow_dispatch:

jobs:
  build:
    strategy: 
      fail-fast: false
      matrix:
        sistema_operativo: [ubuntu-latest, windows-latest, macos-latest]
    name: matriz uni-dimensional
    runs-on: ${{ matrix.sistema_operativo }}
    steps:
      - name: Imprimir SO
        run: echo "Estamos usando el sistema operativo ${{ matrix.sistema_operativo}}"
